<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhimSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('phims')->insert([
            [
                'id' => 1,
                'ten' => 'THẾ GIỚI KHỦNG LONG: LÃNH ĐỊA',
                'thoiluong' => 147,
                'dien_vien' => 'Chris Pratt, Bryce Dallas Howard, Isabella Sermon, Omar Sy, Sam Neill',
                'tom_tat' => 'Bốn năm sau kết thúc Jurassic World: Fallen Kingdom, những con khủng long đã thoát khỏi nơi giam cầm và tiến vào thế giới loài người. Giờ đây, chúng xuất hiện ở khắp mọi nơi. Sinh vật to lớn ấy không còn chỉ ở trên đảo như trước nữa mà gần ngay trước mắt, thậm chí còn có thể chạm tới. Owen Grady may mắn gặp lại cô khủng long mà anh và khán giả vô cùng yêu mến - Blue. Tuy nhiên, Blue không đi một mình mà còn đem theo một chú khủng long con khác. Điều này khiến Owen càng quyết tâm bảo vệ mẹ con cô được sinh sống an toàn. Thế nhưng, hai giống loài quá khác biệt. Liệu có thể tồn tại một kỷ nguyên mà khủng long và con người sống chung một cách hòa bình?',
                'poster' => 'images/posters/phim_poster_1.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_1.jpg',
                'dao_dien' => 'Colin Trevorrow',
                'trailer' => 'https://www.youtube.com/embed/0acHODepcF0',
                'ngay_chieu' => date('Y-m-d',strtotime('10-06-2024')),
            ],
            [
                'id' => 2,
                'ten' => 'EM VÀ TRỊNH',
                'thoiluong' => 136,
                'dien_vien' => 'Trần Lực, Avin Lu, Akari Nakatani, Bùi Lan Hương, Hoàng Hà, Lan Thy, Nhật Linh, Phạm Quỳnh Anh…',
                'tom_tat' => 'Cuộc gặp gỡ định mệnh giữa Trịnh Công Sơn và nữ sinh viên Nhật Bản Michiko tại Paris năm 1990 đã mở ra một mối duyên kỳ ngộ. Từ đây bắt đầu hành trình ngược dòng thời gian, khám phá tuổi thanh xuân và tình yêu của người nhạc sĩ tài hoa với các nàng thơ Thanh Thuý, Bích Diễm, Dao Ánh, Khánh Ly, và những tình khúc mà họ lưu lại trong trái tim ông. Bộ phim lãng mạn, mở ra thế giới nhạc Trịnh quyến rũ với những mảnh ghép tình yêu đa sắc, lung linh tuyệt đẹp.',
                'poster' => 'images/posters/phim_poster_2.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_2.jpg',
                'dao_dien' => 'Phan Gia Nhật Linh',
                'trailer' => 'https://www.youtube.com/embed/7_zm73K-Kg8',
                'ngay_chieu' => date('Y-m-d',strtotime('17-06-2024')),
            ],
            [
                'id' => 3,
                'ten' => 'PHI CÔNG SIÊU ĐẲNG MAVERICK',
                'thoiluong' => 130,
                'dien_vien' => 'Tom Cruise, Justin Marks, Peter Craig, Eric Warren Singer',
                'tom_tat' => 'Sau hơn ba mươi năm phục vụ, Pete “Maverick” Mitchell từng nổi danh là một phi công thử nghiệm quả cảm hàng đầu của Hải quân, né tránh cơ hội thăng chức, điều khiến anh cảm thấy bị bó buộc, để trở về làm chính mình.',
                'poster' => 'images/posters/phim_poster_3.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_3.jpg',
                'dao_dien' => 'Joseph Kosinski',
                'trailer' => 'https://www.youtube.com/ZR99nOkEolM',
                'ngay_chieu' => date('Y-m-d',strtotime('27-05-2024')),
            ],
            [
                'id' => 4,
                'ten' => 'HARRY POTTER VÀ CĂN PHÒNG BÍ MẬT (RE-RUN)',
                'thoiluong' => 161,
                'dien_vien' => 'Daniel Radcliff, Emma Watson, Rupert Grint, Bonnie Wright, Kenneth Branagh,...',
                'tom_tat' => 'Phần tiếp theo của loạt phim Harry Potter vẫn tiếp tục xoay quanh bộ ba Harry Potter - Ron Weasley - Hermione Granger. Bộ ba phù thủy sẽ đối mặt với một thử thách mới trong năm học thứ 2 tại trường Hogwarts. Một thế lực hắc ám đang bao trùm ngôi trường phù thủy này, tấn công hàng loạt học sinh và đe dọa mở Phòng Chứa Bí Mật một lần nữa. (Phim chiếu lại)',
                'poster' => 'images/posters/phim_poster_4.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_4.jpg',
                'dao_dien' => 'Chris Columbus',
                'trailer' => 'https://www.youtube.com/embed/TdYq3WrTCBA',
                'ngay_chieu' => date('Y-m-d',strtotime('03-06-2024')),
            ],
            [
                'id' => 5,
                'ten' => 'DORAEMON: NOBITA VÀ CUỘC CHIẾN VŨ TRỤ TÍ HON 2021',
                'thoiluong' => 109,
                'dien_vien' => 'Subaru Kimura, Megumi Oohara, Megumi Oohara, Kakazu Yumi, Seki Tomokazu',
                'tom_tat' => 'Nobita tình cờ gặp được người ngoài hành tinh tí hon Papi, vốn là Tổng thống của hành tinh Pirika, chạy trốn tới Trái Đất để thoát khỏi những kẻ nổi loạn nơi quê nhà. Doraemon, Nobita và hội bạn thân dùng bảo bối đèn pin thu nhỏ biến đổi theo kích cỡ giống Papi để chơi cùng cậu bé. Thế nhưng, một tàu chiến không gian tấn công cả nhóm. Cảm thấy có trách nhiệm vì liên lụy mọi người, Papi quyết định một mình đương đầu với quân phiến loạn tàn ác. Doraemon và các bạn lên đường đến hành tinh Pirika, sát cánh bên người bạn của mình.',
                'poster' => 'images/posters/phim_poster_5.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_5.jpg',
                'dao_dien' => 'Yamaguchi Susumu',
                'trailer' => 'https://www.youtube.com/embed/XsWx71aokYE',
                'ngay_chieu' => date('Y-m-d',strtotime('27-05-2024')),
            ],
            [
                'id' => 6,
                'ten' => 'MAIKA - CÔ BÉ ĐẾN TỪ HÀNH TINH KHÁC',
                'thoiluong' => 108,
                'dien_vien' => 'Chu Diệp Anh, Lại Trường Phú, Tin Tin, Huy Me, Ngọc Tưởng, Tiểu Bảo Quốc.',
                'tom_tat' => 'Hùng là cậu bé 8 tuổi mồ côi mẹ, sống với cha nhưng tình cảm cha con không khăng khít. Sau khi người bạn thân nhất của Hùng phải chuyển nhà, bố con cậu cũng bị chủ nhà ép chuyển đi. Cậu bé thường tìm kiếm niềm an ủi bằng cách ngắm bầu trời đêm. Một đêm có mưa sao băng, cậu thấy một ngôi sao rơi xuống vùng đất gần đó. Khi Hùng đi tìm, cậu không thấy ngôi sao nào mà thấy một cô bé. Hai đứa trẻ kết thân và giúp đỡ nhau.',
                'poster' => 'images/posters/phim_poster_6.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_6.jpg',
                'dao_dien' => 'Hàm Trần',
                'trailer' => 'https://www.youtube.com/embed/mOH-VKJBsh8',
                'ngay_chieu' => date('Y-m-d',strtotime('27-05-2024')),
            ],
            [
                'id' => 7,
                'ten' => 'ĐẠI NÁO CUNG TRĂNG',
                'thoiluong' => 84,
                'dien_vien' => 'Aleks Le, Howard Nightingall, Lilian Gartner, Raphael von Bargen, Drew Sarich, Cindy Robinson',
                'tom_tat' => 'Chuyến phiêu lưu đến Mặt Trăng của Peter bắt đầu khi em gái cậu, Anne, bị tên Trăng Tặc độc ác bắt cóc khi cô bé đang cố gắng giúp Bác Bọ Zoomzeman tìm lại vợ của mình. Trong cuộc hành trình đầy bất ngờ ấy, Peter gặp Thần Ngủ ở Đồng Cỏ Sao. Để giải cứu Anne, họ đã cùng nhau tham gia một cuộc đua kỳ thú dọc Dải Ngân Hà với 5 vị thần thiên nhiên: Ngài Bão Tố, Phù Thủy Sấm, Ngài Mưa Đá, Bậc Thầy Mưa Gió, và Bà Chúa Tuyết.',
                'poster' => 'images/posters/phim_poster_7.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_7.jpg',
                'dao_dien' => 'Ali Samadi Ahadi',
                'trailer' => 'https://www.youtube.com/embed/i7TezW5eueI',
                'ngay_chieu' => date('Y-m-d',strtotime('03-06-2024')),
            ],
            [
                'id' => 8,
                'ten' => 'CHUYẾN PHIÊU LƯU CỦA PIL',
                'thoiluong' => 89,
                'dien_vien' => 'Kaycie Chase, Paul Borne, Julien Crampon…',
                'tom_tat' => 'Ngày xửa ngày xưa, có một cô bé mồ côi phải trở thành nàng công chúa bất đắc dĩ không giống ai. Một ngày nọ, hoàng tử bị một tên quan độc ác đầu độc và khiến Pil cùng những người bạn phải đứng lên bảo vệ mình và cả vương quốc.',
                'poster' => 'images/posters/phim_poster_8.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_8.jpg',
                'dao_dien' => 'Julien Fournet',
                'trailer' => 'https://www.youtube.com/embed/yeGjaYJPM44',
                'ngay_chieu' => date('Y-m-d',strtotime('01-06-2024')),
            ],
            [
                'id' => 9,
                'ten' => 'VỰC THẲM',
                'thoiluong' => 86,
                'dien_vien' => 'Brittany Ashworth, Ben Lamb, Nathan Welsh',
                'tom_tat' => 'Chuyến leo núi thám hiểm của 2 người bạn thân nhanh chóng trở thanh cơn ác mộng khi bị 4 kẻ sát nhân truy đuổi. Chọn đường nào để sống sót khi trước mặt là vực thẳm và bọn truy sát đã bao vây mọi đường lui?',
                'poster' => 'images/posters/phim_poster_9.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_9.jpg',
                'dao_dien' => 'Howard J. Ford',
                'trailer' => 'https://www.youtube.com/embed/KVC6T8H-UTg',
                'ngay_chieu' => date('Y-m-d',strtotime('03-06-2024')),
            ],
            [
                'id' => 10,
                'ten' => "MOBILE SUIT GUNDAM: CUCURUZ DOAN's ISLAND",
                'thoiluong' => 108,
                'dien_vien' => 'Shunsuke Takeuchi, Toru Furuya, Atsushi Miyauchi, Ayaka Asai',
                'tom_tat' => 'Sau trận chiến ở Jaburo, lực lượng liên bang trái đất lên kế hoạch cho một chiến dịch đánh chiếm Odessa, trụ sở của Lực lượng tấn công Zeon. Tàu chiến White Base trên đường hướng đến Belfast để tiếp tế thì nhận được một mệnh lệnh mới: tìm đường đến hòn đảo được mệnh danh là Đảo Một Đi Không Trở Lại.',
                'poster' => 'images/posters/phim_poster_10.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_10.jpg',
                'dao_dien' => 'Yoshikazu Yasuhiko',
                'trailer' => 'https://www.youtube.com/embed/RSN9TOaJ1rc',
                'ngay_chieu' => date('Y-m-d',strtotime('03-06-2024')),
            ],
            [
                'id' => 11,
                'ten' => 'PHÙ THỦY TỐI THƯỢNG TRONG ĐA VŨ TRỤ HỖN LOẠN',
                'thoiluong' => 126,
                'dien_vien' => 'Benedict Cumberbatch, Elizabeth Olsen Rachel McAdams',
                'tom_tat' => 'Sau các sự kiện của Avengers: Endgame, Tiến sĩ Stephen Strange tiếp tục nghiên cứu về Viên đá Thời gian. Nhưng một người bạn cũ đã trở thành kẻ thù tìm cách tiêu diệt mọi phù thủy trên Trái đất, làm xáo trộn kế hoạch của Strange và cũng khiến anh ta mở ra một tội ác khôn lường.',
                'poster' => 'images/posters/phim_poster_11.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_11.jpg',
                'dao_dien' => 'Sam Raimi',
                'trailer' => 'https://www.youtube.com/embed/nBNtRvpCmms',
                'ngay_chieu' => date('Y-m-d',strtotime('04-05-2024')),
            ],
            [
                'id' => 12,
                'ten' => 'HẦM KHẢI HUYỀN',
                'thoiluong' => 93,
                'dien_vien' => 'Elisha Cuthbert, Eoin Macken, Dylan Fitzmaurice Brady',
                'tom_tat' => 'Câu chuyện bắt đầu khi Ellie, con gái của Keira mất tích. Sau nhiều lần báo cáo cảnh sát nhưng không có manh mối, Keira vô tình phát hiện ra con gái đang bị một thực thể cổ xưa bắt giữ trong chính ngôi nhà của mình. Liệu Keira có cứu được Ellie hay sẽ phải mất đi linh hồn của con mình mãi mãi?',
                'poster' => 'images/posters/phim_poster_12.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_12.jpg',
                'dao_dien' => 'Brendan Muldowney',
                'trailer' => 'https://www.youtube.com/embed/WsuSQrzAIek',
                'ngay_chieu' => date('Y-m-d',strtotime('27-05-2024')),
            ],
            [
                'id' => 13,
                'ten' => 'CẢNH SÁT VŨ TRỤ LIGHTYEAR',
                'thoiluong' => null,
                'dien_vien' => 'Chris Evans, Keke Palmer, Peter Sohn, Taika Waititi, Dale Soules, James Brolin, Uzo Aduba, Mary McDonald-Lewis, Isiah Whitlock Jr., Efren Ramirez, Keira Hairston',
                'tom_tat' => 'Bộ phim kể về chuyến hành trình hành động kết hợp khoa học viễn tưởng nhằm giới thiệu câu chuyện về nguồn gốc của nhân vật Buzz Lightyear — người anh hùng đã truyền cảm hứng sáng tạo ra đồ chơi. “Lightyear” sẽ theo chân Cảnh Sát Vũ Trụ huyền thoại trong cuộc hành trình bước ra ngoài không gian cùng với một nhóm chiến binh đầy tham vọng và người bạn đồng hành là chú mèo máy Sox.',
                'poster' => 'images/posters/phim_poster_13.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_13.jpg',
                'dao_dien' => 'Angus MacLane',
                'trailer' => 'https://www.youtube.com/embed/hB_JdXDnZVQ',
                'ngay_chieu' => date('Y-m-d',strtotime('17-06-2024')),
            ],
            [
                'id' => 14,
                'ten' => 'HARRY POTTER VÀ TÙ NHÂN AZKABAN (RE-RUN)',
                'thoiluong' => 141,
                'dien_vien' => 'Daniel Radcliffe, Emma Watson, Rupert Grint, Gary Oldman, Alan Rickman, Tom Felton',
                'tom_tat' => 'Năm thứ ba của Harry Potter bắt đầu trở nên tồi tệ khi Harry phát hiện ra tên sát nhân Sirius Black đã trốn thoát khỏi nhà tù Azkaban và đang tìm đến Harry để trả thù. Một loạt cai ngục Azkaban được cử đến để bảo vệ Hogwarts và truy đuổi Sirius Black. Một giáo viên bí ẩn đã xuất hiện để dạy Harry Potter cách bảo vệ bản thân. Tuy nhiên, Harry dần phát hiện ra bí mật của mối quan hệ giữa Harry và tên sát nhân Sirius Black phức tạp hơn cậu nghĩ. (Re-run)',
                'poster' => 'images/posters/phim_poster_14.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_14.jpg',
                'dao_dien' => 'Alfonso Cuarón',
                'trailer' => 'https://www.youtube.com/embed/BsSmcJcu854',
                'ngay_chieu' => date('Y-m-d',strtotime('17-06-2024')),
            ],
            [
                'id' => 15,
                'ten' => 'ĐIỆN THOẠI ĐEN',
                'thoiluong' => null,
                'dien_vien' => 'Mason Thames, Madeleine McGraw, Jeremy Davies',
                'tom_tat' => 'Finney Shaw, một cậu bé 13 tuổi nhút nhát nhưng thông minh, bị một kẻ giết người tàn bạo bắt cóc và nhốt trong một tầng hầm cách âm, nơi tiếng la hét trở nên vô ích. Khi một chiếc điện thoại bị ngắt kết nối trên tường bắt đầu đổ chuông, Finney phát hiện ra rằng cậu có thể nghe thấy giọng nói từ những nạn nhân trước đây của kẻ giết người. Và họ đã cố gắng đảm bảo rằng những gì đã xảy ra với họ không xảy ra với Finney.',
                'poster' => 'images/posters/phim_poster_15.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_15.jpg',
                'dao_dien' => 'Scott Derrickson',
                'trailer' => 'https://www.youtube.com/embed/oJr_dYFUaCM',
                'ngay_chieu' => date('Y-m-d',strtotime('24-06-2024')),
            ],
            [
                'id' => 16,
                'ten' => 'ELVIS',
                'thoiluong' => 160,
                'dien_vien' => 'Austin Butler, Tom Hanks, Olivia DeJonge',
                'tom_tat' => 'Chuyện phim ELVIS khám phá những khía cạnh trong cuộc đời cũng như âm nhạc của Elvis Presley (Austin Butler) thông qua lăng kính về mối quan hệ phức tạp của ông với người quản lý Tom Parker (Tom Hanks). Được kể từ góc nhìn của Parker, phim đào sâu vào sự liên kết của Presley và Parker trong suốt 20 năm, từ lúc cậu trai trẻ Presley vụt sáng thành sao trong bối cảnh xã hội Mỹ rối ren và văn hóa đại chúng ngày một phát triển. Trung tâm của hành trình đó là một trong những người có ảnh hưởng sâu sắc nhất trong cuộc đời của Elvis, Priscilla Presley (Olivia DeJonge).',
                'poster' => 'images/posters/phim_poster_16.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_16.jpg',
                'dao_dien' => 'Baz Luhrmann',
                'trailer' => 'https://www.youtube.com/embed/6V9yimqlDew',
                'ngay_chieu' => date('Y-m-d',strtotime('24-06-2024')),
            ],
            [
                'id' => 17,
                'ten' => 'NGƯỜI MÔI GIỚI',
                'thoiluong' => null,
                'dien_vien' => 'Song Kang Ho, Gang Dong Won, Doona Bae, Lee Ji Eun, Lee Joo Young',
                'tom_tat' => 'Sang-hyun (Song Kang Ho) là chủ một cửa tiệm giặt ủi ngập đầu trong nợ nần. Dong-soo (Gang Dong Won) – từng là trẻ mồ côi và hiện đang làm việc cho một cơ sở vận hành “chiếc hộp em bé”. Vào một đêm mưa gió, Sang-hyun và Dong-soo lén lút mang đi một đứa bé vừa bị bỏ rơi trong hộp. Trớ trêu thay, bà mẹ trẻ So-young (Lee Ji Eun) đột nhiên đổi ý và quay trở lại tìm con mình. Dù bán tín bán nghi, So-young quyết định tham gia vào chuyến đi kỳ lạ tìm kiếm gia đình mới cho chính con mình. Trong lúc đó, nữ cảnh sát Soo-jin (Doona Bae) cùng cấp dưới của mình, cảnh sát Lee (Lee Joo Young) đã luôn theo sát và chứng kiến toàn bộ quá trình. Họ lặng lẽ theo dõi bộ ba để thu thập những bằng chứng mang tính quyết định. Cuộc hành trình bám theo những người môi giới của các thanh tra sẽ diễn biến theo một chiều hướng mà chính họ cũng không thể lường trước được. Tất cả mọi chuyện đều bắt đầu từ “chiếc hộp em bé”.',
                'poster' => 'images/posters/phim_poster_17.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_17.jpg',
                'dao_dien' => 'Kore-eda Hirokazu',
                'trailer' => 'https://www.youtube.com/embed/QdW028Rqctk',
                'ngay_chieu' => date('Y-m-d',strtotime('24-06-2024')),
            ],
            [
                'id' => 18,
                'ten' => 'Dragon Ball Super: SUPER HERO',
                'thoiluong' => null,
                'dien_vien' => 'Masako Nozawa, Toshio Furukawa, Yūko Minaguchi, Ryō Horikawa, Mayumi Tanaka, Aya Hisakawa, Takeshi Kusao, Miki Itō,...',
                'tom_tat' => 'Đội quân Ruy Băng Đỏ đã bị Son Goku tiêu diệt. Thế nhưng, những kẻ kế nghiệp của chúng đã tạo ra hai chiến binh Android mới là Gamma 1 và Gamma 2. Hai Android này tự nhận mình là “Siêu anh hùng”. Chúng bắt đầu tấn công Piccolo và Gohan… Mục tiêu của Đội quân Ruy Băng Đỏ mới này là gì? Trước nguy cơ cận kề, đã đến lúc các siêu anh hùng thực thụ phải thức tỉnh!',
                'poster' => 'images/posters/phim_poster_18.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_18.jpg',
                'dao_dien' => 'Tetsuro Kodama',
                'trailer' => 'https://www.youtube.com/embed/C9KHj81O_L0',
                'ngay_chieu' => null,
            ],
            [
                'id' => 19,
                'ten' => 'MINIONS: SỰ TRỖI DẬY CỦA GRU',
                'thoiluong' => null,
                'dien_vien' => 'Steve Carell, Lucy Lawless, Michelle Yeoh...',
                'tom_tat' => 'Hành trình phiêu lưu của #Gru song hành cùng với #Otto và viên đá của ác nhân MINIONS: SỰ TRỖI DẬY CỦA GRU - DCKC: 2024',
                'poster' => 'images/posters/phim_poster_19.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_19.jpg',
                'dao_dien' => 'Kyle Balda, Brad Ableson, Jonathan del Val',
                'trailer' => 'https://www.youtube.com/embed/dTQXlDV16SY',
                'ngay_chieu' => date('Y-m-d',strtotime('01-07-2024')),
            ],
            [
                'id' => 20,
                'ten' => 'THOR: TÌNH YÊU VÀ SẤM SÉT',
                'thoiluong' => null,
                'dien_vien' => 'Chris Hemsworth, Tessa Thompson, Natalie Portman, Chris Pratt',
                'tom_tat' => 'Vốn từng là một chiến binh hùng mạnh của Asgard, trải qua vô số trận chiến lớn nhỏ nhưng sau sự kiện trong Avengers: Endgame (2019) cùng vô số mất mát, Thần Sấm không còn muốn theo đuổi con đường siêu anh hùng. Từ đây, anh lên đường tìm ra ý nghĩa của cuộc sống và nhìn nhận lại bản thân mình.',
                'poster' => 'images/posters/phim_poster_20.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_20.jpg',
                'dao_dien' => 'Taika Waititi',
                'trailer' => 'https://www.youtube.com/embed/6_dk-s57jck',
                'ngay_chieu' => date('Y-m-d',strtotime('08-07-2024')),
            ],
            [
                'id' => 21,
                'ten' => 'PORORO: CUỘC PHIÊU LƯU ĐẾN ĐẢO KHỦNG LONG',
                'thoiluong' => null,
                'dien_vien' => 'trtrt',
                'tom_tat' => 'Pororo và những người bạn tìm thấy chú khủng long nhỏ Alo đang ngủ say trong chiếc phi thuyền hình quả trứng. Alo không nhớ gì ngoài tên của mình. Khi Pororo và bạn bè giúp Alo sửa phi thuyền thì phi thuyền vụt sáng và biến mất cùng Alo và người bạn của Pororo là Crong. Pororo đuổi theo chiếc phi thuyền đến Đảo Khủng Long và chạm trán với Mr.Y, kẻ chuyên bắt cóc khủng long để bán cho người ngoài hành tinh. Để giải cứu bạn của mình, Pororo phải vượt qua nỗi sợ khủng long để chiến đấu với người ngoài hành tinh và đội quân người máy của Mr.Y.',
                'poster' => 'images/posters/phim_poster_21.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_21.jpg',
                'dao_dien' => 'Kim Hyunho, Yoon Jewan',
                'trailer' => 'https://www.youtube.com/embed/4dxVVwLSPlA',
                'ngay_chieu' => date('Y-m-d',strtotime('15-07-2024')),
            ],
            [
                'id' => 22,
                'ten' => 'QUYẾT TÂM CHIA TAY',
                'thoiluong' => null,
                'dien_vien' => 'Tang Wei, Park Hae Il',
                'tom_tat' => 'Một thanh tra cảnh sát rơi vào lưới tình với goá phụ trẻ - nghi phạm giết người trong vụ án mà anh ta đang điều tra.',
                'poster' => 'images/posters/phim_poster_22.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_22.jpg',
                'dao_dien' => 'Park Chan Wook',
                'trailer' => 'https://www.youtube.com/embed/mTiNtVzysWU',
                'ngay_chieu' => date('Y-m-d',strtotime('15-07-2024')),
            ],
            [
                'id' => 23,
                'ten' => 'THÁM TỬ LỪNG DANH CONAN: NÀNG DÂU HALLOWEEN',
                'thoiluong' => null,
                'dien_vien' => 'Minami Takayama, Chafûrin, Tôru Furuya',
                'tom_tat' => 'Tại Shibuya náo nhiệt mùa Halloween, Thiếu úy Sato Miwako khoác lên mình chiếc váy cưới tinh khôi trong tiệc cưới như cổ tích, và người đàn ông bên cạnh cô không ai khác ngoài Trung sĩ Takagi Wataru. Trong giây phút trọng đại, một nhóm người xấu ập vào tấn công, Trung sĩ Takagi liều mình bảo vệ Sato. Anh tai qua nạn khỏi, nhưng Sato chết lặng khi nhìn thấy bóng ma Thần Chết trong giây phút sinh tử của Takagi. Điều này khiến cô nhớ lại cái chết của đồng nghiệp, cũng là người cô từng yêu trước đây, Thanh tra Matsuda Jinpei. Cùng lúc này, hung thủ của vụ đánh bom liên tiếp mà Matsuda điều tra năm xưa đã vượt ngục thành công. Khi Conan tìm đến Furuya Rei (hay Amuro Toru), người bạn cùng khóa với Matsuda, cậu được nghe câu chuyện liên quan đến vụ đánh bom với kẻ thủ ác mang bí danh "Plamya". Hôn lễ nguy hiểm nhất thế giới, buổi dạ hành đẫm máu tại Shibuya vào đêm Halloween sắp sửa bắt đầu.',
                'poster' => 'images/posters/phim_poster_23.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_23.jpg',
                'dao_dien' => 'Gosho Aoyama, Susumu Mitsunaka',
                'trailer' => 'https://www.youtube.com/embed/SqSJPzWvcLc',
                'ngay_chieu' => date('Y-m-d',strtotime('22-07-2024')),
            ],
            [
                'id' => 24,
                'ten' => 'DÂN CHƠI KHÔNG SỢ CON RƠI',
                'thoiluong' => null,
                'dien_vien' => 'Tiến Luật, bé Bảo Thi, Huỳnh Phương, Nguyên Thảo, Vân Trang, Ngô Kiến Huy, Lê Khánh,...',
                'tom_tat' => 'Quân, một dân chơi miệt vườn với tài “sát gái” thượng hạng, bỗng một ngày phải gánh lấy "cục nợ con rơi" từ bạn gái cũ. Được sự trợ giúp "ba phần đắc lực bảy phần phá đám" của Tám Mánh, Quân dần mất hết hy vọng tìm lại mẹ cho đứa bé và dần trở thành người cha hoàn hảo trong mắt Bé Thỏ. Cuộc sống đầy sắc màu và tiếng cười của hai cha con bị đặt trước thử thách lớn lao khi người mẹ mà Bé Thỏ ngày đêm mong ngóng cuối cùng cũng xuất hiện…',
                'poster' => 'images/posters/phim_poster_24.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_24.jpg',
                'dao_dien' => 'Huỳnh Đông',
                'trailer' => 'https://www.youtube.com/embed/A4mSS-xmiMM',
                'ngay_chieu' => date('Y-m-d',strtotime('29-07-2024')),
            ],
            [
                'id' => 25,
                'ten' => 'AVATAR: DÒNG CHẢY CỦA NƯỚC',
                'thoiluong' => null,
                'dien_vien' => 'Sam Worthington, Zoe Saldana, Dương Tử Quỳnh,...',
                'tom_tat' => 'Câu chuyện của “Avatar: Dòng Chảy Của Nước” lấy bối cảnh 10 năm sau những sự kiện xảy ra ở phần đầu tiên. Phim kể câu chuyện về gia đình mới của Jake Sully (Sam Worthington thủ vai) cùng những rắc rối theo sau và bi kịch họ phải chịu đựng khi phe loài người xâm lược hành tinh Pandora.',
                'poster' => 'images/posters/phim_poster_25.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_25.jpg',
                'dao_dien' => 'James Cameron',
                'trailer' => 'https://www.youtube.com/embed/S3dNmMZE9sc',
                'ngay_chieu' => null,
            ],
            [
                'id' => 26,
                'ten' => 'QUỲNH HOA NHẤT DẠ',
                'thoiluong' => null,
                'dien_vien' => 'Thanh Hằng',
                'tom_tat' => 'Phim dã sử về cuộc đời Thái hậu Dương Vân Nga.',
                'poster' => 'images/posters/phim_poster_26.jpg',
                'thumbnail' => 'images/thumbnails/phim_thumbnail_26.jpg',
                'dao_dien' => 'Lý Minh Thắng',
                'trailer' => 'https://www.youtube.com/embed/KTGgulcoMmU',
                'ngay_chieu' => null,
                
            ]

        ]);
    }
}
